<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WiFi;
use Illuminate\Support\Facades\DB;

class WifiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('wifi')->insert([
            [
                'nama' => 'Area Gedung KNPI',
                'lokasi' => 'https://maps.app.goo.gl/rySijN69D1u34CQE8',
                'titik' => '-7.215874, 107.903069',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Alun Alun Garut',
                'lokasi' => 'https://maps.app.goo.gl/chHnznJb9VYQwpuP7',
                'titik' => '-7.215970, 107.901411',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'AREA MESJID AGUNG',
                'lokasi' => 'https://maps.app.goo.gl/Y4aqLd3sr9sZwHaB8',
                'titik' => '-7.215943, 107.900763',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'AREA LAPANG KERKOF',
                'lokasi' => 'https://maps.app.goo.gl/ouNktZXUEMa85aby9',
                'titik' => '-7.206970, 107.901881',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'PPDI',
                'lokasi' => 'https://maps.app.goo.gl/t1A82k8aPrVYWJNH7',
                'titik' => '-7.204993, 107.887217',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KWARTIR CABANG PRAMUKA',
                'lokasi' => 'https://maps.app.goo.gl/V7hkoTdmPaSovoqj7',
                'titik' => '-7.223690, 107.905607',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'AREA HALAMAN DISDUKCAPIL',
                'lokasi' => 'https://maps.app.goo.gl/tjSGarYgLgyXvuHEA',
                'titik' => '-7.202092, 107.885273',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'AREA LAPANG JAYARAGA',
                'lokasi' => 'https://maps.app.goo.gl/9rGZ5VuRX7ZJNCeA6',
                'titik' => '-7.207373, 107.897432',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'PSSI GARUT',
                'lokasi' => 'https://maps.app.goo.gl/jhGY3cdRS9KfoQW38',
                'titik' => '-7.208082, 107.898193',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'LAPANG SETDA 1',
                'lokasi' => 'https://maps.app.goo.gl/5YV3FM7s2nKiJY1ZA',
                'titik' => '-7.202702, 107.886665',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'LAPANG SETDA 2',
                'lokasi' => 'https://maps.app.goo.gl/5YV3FM7s2nKiJY1ZA',
                'titik' => '-7.202651, 107.886118',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'RTP KEL CIWALEN (RW 10 BELAKANG BETHESDA)',
                'lokasi' => 'https://maps.app.goo.gl/NC76ioKXPGHJ6YfC8',
                'titik' => '-7.214681, 107.909351',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'TAMAN MAKTAL',
                'lokasi' => 'https://maps.app.goo.gl/NueBydVf5n7GijPZ8',
                'titik' => '-7.219333, 107.900046',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'HALAMAN BJB',
                'lokasi' => 'https://maps.app.goo.gl/528LpqnuTp1NC4tb8',
                'titik' => '-7.215869, 107.904381',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ALUN ALUN TAROGONG KALER',
                'lokasi' => 'https://maps.app.goo.gl/kTG9fJYSoAvjZxgEA',
                'titik' => '-7.190168, 107.889693',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ALUN ALUN WANARAJA',
                'lokasi' => 'https://maps.app.goo.gl/pcheSDjwqrXUzeFF9',
                'titik' => '-7.173001, 107.981296',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ALUN ALUN LIMBANGAN',
                'lokasi' => 'https://maps.app.goo.gl/1afgShJgnUWM4qur6',
                'titik' => '-7.034773, 107.984804',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ALUN ALUN PAMENGPEUK',
                'lokasi' => 'https://maps.app.goo.gl/zD5DAfkzHswjY61v7',
                'titik' => '-7.644572, 107.727961',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ALUN ALUN BAYONGBONG',
                'lokasi' => 'https://maps.app.goo.gl/Pq7mPtDAqPt4M1hH9',
                'titik' => '-7.270237, 107.820758',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CIKELET',
                'lokasi' => 'https://maps.app.goo.gl/Sxat9Bkz1oTHcLiB9',
                'titik' => '-7.618804, 107.674947',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CIBALONG',
                'lokasi' => 'https://maps.app.goo.gl/MDxBvK8QchBgwWdP6',
                'titik' => '-7.678600, 107.803538',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CIHURIP',
                'lokasi' => 'https://maps.app.goo.gl/TUUC5hqqrMsWKTL29',
                'titik' => '-7.495680, 107.858571',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CISOMPET',
                'lokasi' => 'https://maps.app.goo.gl/KZvyHL4N29pgUfd4A',
                'titik' => '-7.551112, 107.811332',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC BANJARWANGI',
                'lokasi' => 'https://maps.app.goo.gl/Ca1RFSPLzwbWd9u8A',
                'titik' => '-7.442145, 107.904818',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC PENDEUY',
                'lokasi' => 'https://maps.app.goo.gl/2BuxLT7G2e9mwX4RA',
                'titik' => '-7.528240, 107.918961',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CARINGIN',
                'lokasi' => 'https://maps.app.goo.gl/DfDJ7xpdnn51jqbU8',
                'titik' => '-7.522870, 107.489065',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CISEWU',
                'lokasi' => 'https://maps.app.goo.gl/cC8cpao4tmXgteQC7',
                'titik' => '-7.377414, 107.501280',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC TALEGONG',
                'lokasi' => 'https://maps.app.goo.gl/eFwv2GQuMbUfeope9',
                'titik' => '-7.286397, 107.528713',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC BUNGBULANG',
                'lokasi' => 'https://maps.app.goo.gl/WM6Ly1WxEtgo11ht7',
                'titik' => '-7.455539, 107.598837',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC MEKARMUKTI',
                'lokasi' => 'https://maps.app.goo.gl/gWCWdjvmb2o3d2cz9',
                'titik' => '-7.545026, 107.570711',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC PAKENJENG',
                'lokasi' => 'https://maps.app.goo.gl/cmhwKugxUAPUKZxL8',
                'titik' => '-7.465071, 107.671503',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC PAMULIHAN',
                'lokasi' => 'https://maps.app.goo.gl/q7ezaHMt2XiXXpqX8',
                'titik' => '-7.410035, 107.691655',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CIKAJANG',
                'lokasi' => 'https://maps.app.goo.gl/jNNNArRMYJsXtjdS6',
                'titik' => '-7.357253, 107.809479',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC KARANGPAWITAN',
                'lokasi' => 'https://maps.app.goo.gl/zsvDSzy9Frwr2bPN7',
                'titik' => '-7.205731, 107.946856',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC CIBATU',
                'lokasi' => 'https://maps.app.goo.gl/zd9Rm1uT8Z5zAtmu5',
                'titik' => '-7.101318, 107.983627',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'KANTOR KEC LELES',
                'lokasi' => 'https://maps.app.goo.gl/Lnr7Z8maQypS3jgbA',
                'titik' => '-7.108859, 107.898499',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'LPTQ',
                'lokasi' => 'https://maps.app.goo.gl/jhzBjWWKNgvZssgu8',
                'titik' => '-7.184567, 107.876912',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'SOR CIATEUL',
                'lokasi' => 'https://maps.app.goo.gl/MNmDiq75y6nEvULh8',
                'titik' => '-7.193108, 107.902645',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'GEDUNG PKK',
                'lokasi' => 'https://maps.app.goo.gl/ri1kvM5CjcEbomcc7',
                'titik' => '-7.217303, 107.901353',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ART CENTER',
                'lokasi' => 'https://maps.app.goo.gl/5TuafFvHJY3z7GVA6',
                'titik' => '-7.192007, 107.900470',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'SENTRA IKAN',
                'lokasi' => 'https://maps.app.goo.gl/bbWqTvhRYfMArxJj7',
                'titik' => '-7.182762, 107.889672',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'SITU BAGENDIT',
                'lokasi' => 'https://maps.app.goo.gl/AGbKFEyXCi18H2sz6',
                'titik' => '-7.159839, 107.951083',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'PMI',
                'lokasi' => 'https://maps.app.goo.gl/QeW1SheKoLk6CTJc7',
                'titik' => '-7.191262, 107.899657',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'GUNTUR SIMPANG ASIA',
                'lokasi' => 'https://maps.app.goo.gl/7NAq7mecLL3DZPQ68',
                'titik' => '-7.215911, 107.908742',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'BALE PAMINTON',
                'lokasi' => 'https://maps.app.goo.gl/23Sb7o4Qp3hrPLdL7',
                'titik' => '-7.215878, 107.903326',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'PASAR CEPLAK',
                'lokasi' => 'https://maps.app.goo.gl/9up5Dvne6Qyho13Q7',
                'titik' => '-7.216810, 107.904958',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'WIFI PUBLIC PERTIGAAN Jl.Patriot',
                'lokasi' => 'https://maps.app.goo.gl/BaqSGvFDq8wko5Yb9',
                'titik' => '-7.203018, 107.885447',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'TAMAN KULINER CIBATU',
                'lokasi' => 'https://maps.app.goo.gl/LKFVTZe4NhzQFxDM9',
                'titik' => '-7.097688, 107.983715',
                'ssid' => 'wifi public garut diskominfo',
                'password' => 'Gacor1',
                'status' => 'Online',
                'status_validasi' => 'Pending',
                'komentar' => null,
                'total_pengguna' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}
